services:
  mongo:
    image: mongo:6.0 # Use a specific version for stability
    container_name: mongo
    ports:
      - "27017:27017" # Maps container port 27017 to host port 27017
    volumes:
      - mongo_data:/data/db # Persist MongoDB data

  spring-app:
    build: . # Build from the Dockerfile in the current directory
    container_name: demo-flywaycrud-2025
    depends_on:
      - mongo # Ensures mongo starts before spring-app
    ports:
      - "8080:8080" # Maps container port 8080 to host port 8080
    environment:
      # Pass Spring properties as environment variables (overrides application.properties)
      SPRING_APPLICATION_NAME: demo-flywaycrud-2025
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/demo-flywaycrud-2025
      SPRING_FLYWAY_URL: jdbc:mongo://mongo:27017/demo-flywaycrud-2025
      SPRING_FLYWAY_DRIVER_CLASS_NAME: com.dbschema.MongoJdbcDriver
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_SQL_MIGRATION_SUFFIXES: .js
    # Ensure the app stays up if it exits prematurely (useful for debugging)
    # restart: on-failure

volumes:
  mongo_data: # Define the volume for MongoDB data persistence
