

name: CI with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v3

      # 2️⃣ Set up Docker Buildx
      - uses: docker/setup-buildx-action@v2

      # 3️⃣ Build and start Docker Compose services
      - name: Build and start Docker Compose
        run: docker-compose up --build -d

      # 4️⃣ Wait for MongoDB to be ready
      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB..."
          for i in {1..30}; do
            docker exec mongo mongosh --eval "db.adminCommand('ping')" && break
            echo "MongoDB not ready yet, sleeping 2 seconds..."
            sleep 2
          done

      # 5️⃣ Run Gradle build and tests inside Spring Boot container
      # ❌ No --scan, so dependency submission error will not happen
      - name: Run Gradle tests
        run: docker exec demo-flywaycrud-2025 ./gradlew build test --no-daemon

      # 6️⃣ Upload test reports as artifacts
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: ./build/reports/tests/test

      # 7️⃣ Tear down Docker Compose
      - name: Tear down Docker Compose
        run: docker-compose down
