package com.example.demoflywaycrud2025.persistence.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@Document(collection = "contacts") // MongoDB collection name
public class Contact {

    @Id // Automatically generated by MongoDB if null on save
    private String id;

    private String companyName;
    private String email;

    @Field("phone_number") // Maps to 'phone_number' in MongoDB
    private String phoneNumber;

    @Field("employees")
    private String employees;

    @Field("coc_number")
    private String cocNumber;

    @Field("vat_number")
    private String vatNumber;

    @Field("iban_number")
    private String ibanNumber;

    private String description;
    private Double budget;
}
