name: CI with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and start Docker Compose services
      - name: Build and start Docker Compose services
        run: docker-compose up --build -d

      # Wait for MongoDB to be healthy before running tests
      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready..."
          for i in {1..30}; do
            docker exec mongo mongosh --eval "db.adminCommand('ping')" && break
            echo "MongoDB not ready yet, sleeping 2 seconds..."
            sleep 2
          done

      # Run integration tests inside Spring Boot container
      - name: Run Spring Boot integration tests
        run: docker exec demo-flywaycrud-2025 ./gradlew test --no-daemon

      # Optional: Shut down Docker Compose
      - name: Tear down Docker Compose
        run: docker-compose down
