name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  # Linux runner

    # MongoDB service for integration tests
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Make gradlew executable (fixes 'Permission denied')
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Set up Java 17 with Gradle cache
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      # Build project and run tests
      - name: Build with Gradle
        run: ./gradlew build --scan --no-daemon

      # Upload test reports
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test
